/*

 MAP-1.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 30 x 20
   Tile set      : C:\Users\purpl\Desktop\gbtd22\background-1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define map1Width 30
#define map1Height 20
#define map1Bank 0

extern unsigned char map1[];

/* End of MAP-1.H */
