/*

 NEW-BG.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\purpl\Desktop\gbtd22\background-1.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define bg1Width 40
#define bg1Height 18
#define bg1Bank 0

extern unsigned char bg1[];

/* End of NEW-BG.H */
